"""         -----------
@file       settings.py
@brief      Django backend settings for `fsuy_django`...
@date       05-2026
@details    Generated by 'django-admin startproject' using Django 6.0.5.
"""

from pathlib import Path


BASE_DIR: Path = Path(__file__).resolve().parent.parent


#
#
#

DEBUG: bool = True


#
#
#   Loading variables from the environment
#                              -----------
#

import os


#
#   Secret key
#

from django.conf.global_settings import SECRET_KEY

if "DJANGO_SECRET_KEY" in os.environ:
    SECRET_KEY: str = os.environ["DJANGO_SECRET_KEY"]
    print("||| SECRET_KEY secured")

else:
    from django.core.management.utils import get_random_secret_key

    SECRET_KEY: str = get_random_secret_key()
    print("||| SECRET_KEY:", SECRET_KEY)


#
# URL hostname
#

URL_HOSTNAME: str | None = None

if "URL_HOSTNAME" in os.environ:
    URL_HOSTNAME: str = os.environ["URL_HOSTNAME"]


ALLOWED_HOSTS: list[str] = []

if URL_HOSTNAME is not None:
    ALLOWED_HOSTS.append(URL_HOSTNAME)


if not ALLOWED_HOSTS:
    ALLOWED_HOSTS: list[str] = [
        "localhost",
        "127.0.0.1",
    ]


#
#
#   Applications
#
#

INSTALLED_APPS: list[str] = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "fsuy_site"
]

MIDDLEWARE: list[str] = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",


    # MW s.t. static files can be served in production...
    "whitenoise.middleware.WhiteNoiseMiddleware",
]


ROOT_URLCONF: str = "fsuy_django.urls"


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "../frontend/site",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'fsuy_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


#
#
#   Localization
#   ref: https://docs.djangoproject.com/en/6.0/topics/i18n/
#

LANGUAGE_CODE: str = "en-us"

TIME_ZONE: str = "UTC"

USE_I18N: bool = True

USE_TZ: bool = True


#
#
#   Static files
#   ref.: https://docs.djangoproject.com/en/6.0/howto/static-files/
#

STATIC_URL: str = "/static/"
STATIC_ROOT: Path = BASE_DIR / "staticfiles"

STATICFILES_DIRS: list[Path] = [
    BASE_DIR / ".." / "frontend/"
]


#
#
#   HTTPS & Security
#
#

CSRF_COOKIE_SECURE: bool = True
CSRF_COOKIE_SAMESITE: str = "Lax"

SESSION_COOKIE_SECURE: bool = True

X_FRAME_OPTIONS: str = "DENY"


# 'cause without the proxy may terminate the TLS and redirect http to django.
# therefore it makes "request.is_secure()" assertable.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
