"""         -----------
@file       settings.py
@brief      Django backend settings for `fsuy_django`...
@date       05-2026
@details    Intially generated by 'django-admin startproject' using Django 6.0.5.
"""

from pathlib import Path


BASE_DIR: Path = Path(__file__).resolve().parent.parent


#
#   Debug / deployment configs...
#

DEBUG: bool = True
LOCAL_DB: bool = False


#
#
#   Loading variables from the environment
#                              -----------
#

import os


#
#   Secret key
#

from django.conf.global_settings import SECRET_KEY

if "DJANGO_SECRET_KEY" in os.environ:
    SECRET_KEY: str = os.environ["DJANGO_SECRET_KEY"]
    print("||| SECRET_KEY secured")

else:
    from django.core.management.utils import get_random_secret_key

    SECRET_KEY: str = get_random_secret_key()
    print("||| SECRET_KEY:", SECRET_KEY)


#
# URL hostname
#

URL_HOSTNAME: str | None = None

if "URL_HOSTNAME" in os.environ:
    URL_HOSTNAME: str = os.environ["URL_HOSTNAME"]


ALLOWED_HOSTS: list[str] = []

if URL_HOSTNAME is not None:
    ALLOWED_HOSTS.append(URL_HOSTNAME)


if not ALLOWED_HOSTS:
    ALLOWED_HOSTS: list[str] = [
        "localhost",
        "127.0.0.1",
    ]


#
#
#   Applications
#
#

INSTALLED_APPS: list[str] = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "storages",
    "django_extensions",

    "fsuy_site"
]

STORAGES: dict[str, dict] = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key":           os.environ["DATABASE_STORAGE_ACCESS"],
            "secret_key":           os.environ["DATABASE_STORAGE_SECRET"],
            "bucket_name":          "assets",

            "region_name":          os.environ["DATABASE_STORAGE_REGION"],
            "endpoint_url":         f"https://{os.environ['DATABASE_STORAGE_REF']}.supabase.co/storage/v1/s3",
            "signature_version":    "s3v4",
        },
    },

    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


MIDDLEWARE: list[str] = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",


    # MW s.t. static files can be served in production...
    "whitenoise.middleware.WhiteNoiseMiddleware",
]


ROOT_URLCONF: str = "fsuy_django.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "../frontend/site",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


WSGI_APPLICATION = "fsuy_django.wsgi.application"


REST_FRAMEWORK: dict[str, list[str]] = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ]
}


#
#   Database
#   ref.: https://docs.djangoproject.com/en/6.0/ref/settings/#databases

from typing import Any


def choose_database(local_db: bool = True) -> dict[str, Any]:
    """
    Selects the database...

    :return:
    """

    if local_db:
        return {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }

    # getting the env. pass...
    host: str       = os.environ["DATABASE_HOST"]
    password: str   = os.environ["DATABASE_PASSWORD"]
    port: str       = os.environ["DATABASE_PORT"]
    user: str       = os.environ["DATABASE_USER"]

    print(f"Database INFO.: {host}, {password}, {port}, {user}")

    import socket
    print(f"Database connecting to address: {socket.getaddrinfo(host, port)[-1][-1][0]}")

    return {
        "default": {
            "ENGINE":       "django.db.backends.postgresql",
            "NAME":         "postgres",
            "USER":         user,
            "PASSWORD":     password,
            "HOST":         host,
            "PORT":         port,
        }
    }


DATABASES: dict[str, Any] = choose_database(LOCAL_DB)



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_USER_MODEL: str = "fsuy_site.User"


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


#
#
#   Localization
#   ref: https://docs.djangoproject.com/en/6.0/topics/i18n/
#

LANGUAGE_CODE: str = "en-us"

# TIME_ZONE: str = "UTC"
TIME_ZONE: str = "America/Sao_Paulo"

USE_I18N: bool = True
USE_TZ: bool = True


#
#
#   Static files
#   ref.: https://docs.djangoproject.com/en/6.0/howto/static-files/
#

STATIC_URL: str = "/static/"
STATIC_ROOT: Path = BASE_DIR / "staticfiles"

STATICFILES_DIRS: list[Path] = [
    BASE_DIR / ".." / "frontend/"
]


#
#
#   HTTPS & Security
#
#

CSRF_COOKIE_SECURE: bool = True
CSRF_COOKIE_SAMESITE: str = "Lax"

SESSION_COOKIE_SECURE: bool = True

X_FRAME_OPTIONS: str = "DENY"


# 'cause without the proxy may terminate the TLS and redirect http to django.
# therefore it makes "request.is_secure()" assertable.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
