# Generated by Django 6.0.5 on 2026-06-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsuy_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=25)),
                ('launch_date', models.DateField()),
            ],
        ),
    ]
